function plot_TRNSYS_all(TData,Settings)
for i = 1:size(TData,2) % The 2nd element of size output is the number of sub-structures in TData
    figure
    plot_TRNSYS(TData(i).name,...
        TData(i).header,...
        TData(i).units,...
        TData(i).datenum,...
        TData(i).data,Settings.Range);
end
end

