function psy3(action)
if nargin==0
   action='init';
end

switch (action)
case 'init'
   global patm
   global rh
   global tdb
   patm=101.325;						% in kPa
   tdb=30.5;							% in degree C
   rh=50;								% in %
   %-----------------------------------------------------------------------------------------
pws=psy(tdb,0,0,'pws'); 			% in kPa
hfg=psy(tdb,0,0,'hfg'); 				% in kJ/kg
pw=psy(pws,rh,0,'pw');  			% in kPa
ah=psy(patm,pws,rh,'ah'); 			% in kg/kg
ahoftdb=psy(patm,pws,100,'ah'); 	% in kg/kg
tdp=psy(tdb,pw,0,'tdp'); 			% in degree C
h=psy(tdb,ah,0,'h'); 				% in kJ/kg
sv=psy(patm,tdb,ah,'sv'); 			% in m3/kg
dos=psy(patm,pws,rh,'dos');			% in kg/kg
twb=psy(tdb,tdp,0,'twb');			% in degree C
%-------------------------------------------------
z=zeros(1,13);
z(1)=patm; z(2)=tdb; z(3)=twb;z(4)=tdp; z(5)=rh; 
z(6)=dos;z(7)=pws; z(8)=pw;z(9)=ah; z(10)=h; 
z(11)=sv; z(12)=hfg;
%--------------------------------------------------Display Chart
figure('tag','CHART','Resize','off','MenuBar','none',...
   'Name','Psychrometric Chart','NumberTitle','off','Position',[100,100,640,480]);
PSchart;

%-------------------------------------------------set UI position
pos0=[0 220 40 20];              %label position
pos1=[40 220 40 20];					%first No position
pos2=[80 220 80 20];            %second NO position
pos3=[160 220 45 20];            %unit position
pos4=[205 220 110 20];
sqr=[0 20 0 0];                  %separated
%--------------------------------------------------Display Input dialog
figure('tag','INPUT','Resize','on','MenuBar','none',...
   'Name','Input','NumberTitle','off','Position',[200,260,315,240]);

%(1)=patm;(2)=tdb;(3)=twb;(4)=tdp; (5)=rh; 
%(6)=dos; (7)=pws;(8)=pw; (9)=ah;  (10)=h; 
%(11)=sv; (12)=hfg;

t1 = uicontrol('Position',pos0,...
   'string','Patm','style','text','Tag','T1');
t2 = uicontrol('Position',pos0-sqr,...
   'string','Tdb','style','text','Tag','T2');
t3 = uicontrol('Position',pos0-2*sqr,...
   'string','Twb','style','text','Tag','T3');
t4 = uicontrol('Position',pos0-3*sqr,...
   'string','Tdp','style','text','Tag','T4');
t5 = uicontrol('Position',pos0-4*sqr,...
   'string','RH','style','text','Tag','T5');
t6 = uicontrol('Position',pos0-5*sqr,...
   'string','DOS','style','text','Tag','T6');
t7 = uicontrol('Position',pos0-6*sqr,...
   'string','Pws','style','text','Tag','T7');
t8 = uicontrol('Position',pos0-7*sqr,...
   'string','Pw','style','text','Tag','T8');
t9 = uicontrol('Position',pos0-8*sqr,...
   'string','AH','style','text','Tag','T9');
t10 = uicontrol('Position',pos0-9*sqr,...
   'string','h','style','text','Tag','T10');
t11 = uicontrol('Position',pos0-10*sqr,...
   'string','SV','style','text','Tag','T11');
t12 = uicontrol('Position',pos0-11*sqr,...
   'string','hfg','style','text','Tag','T12');

f2 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos1-sqr, ...
   'string',num2str(z(2)),...
   'Style','edit', ...
   'Tag','F2','callback','test1(''cbTdb'')');
f3 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos1-2*sqr, ...
   'Style','text', ...
   'Tag','F3','callback','test1(''cbTwb'')');
f4 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos1-3*sqr, ...
   'Style','text', ...
   'Tag','F4','callback','test1(''cbTdp'')');
f5 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos1-4*sqr, ...
   'Style','text', ...
	'Tag','F5','callback','test1(''cbRH'')');
f8 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos1-7*sqr, ...
   'Style','text', ...
   'Tag','F8','callback','test1(''cbPw'')');
f9 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos1-8*sqr, ...
   'Style','text', ...
   'Tag','F9','callback','test1(''cbAH'')');
f10 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos1-9*sqr, ...
   'Style','text', ...
   'Tag','F10');

h1 = uicontrol('BackgroundColor',[1 1 1], ...
   'Position',pos2, ...
   'string',num2str(z(1)),...
   'Style','text', ...
   'Tag','H1','visible','off');
h2 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos2-sqr, ...
   'string',num2str(z(2)),...
   'Style','edit', ...
   'Tag','H2','visible','off','callback','PsyFixTdb(''cbTdb'')');
h3 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos2-2*sqr, ...
   'string',num2str(z(3)),...
   'Style','edit', ...
   'Tag','H3','visible','off','callback','PsyFixTdb(''cbTwb'')');
h4 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos2-3*sqr, ...
   'string',num2str(z(4)),...
   'Style','edit', ...
   'Tag','H4','visible','off','callback','PsyFixTdb(''cbTdp'')');
h5 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos2-4*sqr, ...
   'string',num2str(z(5)),...
   'Style','edit', ...
	'Tag','H5','visible','off','callback','PsyFixTdb(''cbRH'')');
h6 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos2-5*sqr, ...
   'string',num2str(z(6)),...
   'Style','text', ...
	'Tag','H6','visible','off');
h7 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos2-6*sqr, ...
   'string',num2str(z(7)),...
   'Style','text', ...
	'Tag','H7','visible','off');
h8 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos2-7*sqr, ...
   'string',num2str(z(8)),...
   'Style','edit', ...
   'Tag','H8','visible','off','callback','PsyFixTdb(''cbPw'')');
h9 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos2-8*sqr, ...
   'string',num2str(z(9)),...
   'Style','edit', ...
   'Tag','H9','visible','off','callback','PsyFixTdb(''cbAH'')');
h10 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos2-9*sqr, ...
   'string',num2str(z(10)),...
   'Style','text', ...
   'Tag','H10','visible','off');
h11 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos2-10*sqr, ...
   'string',num2str(z(11)),...
   'Style','text', ...
   'Tag','H11','visible','off');
h12 = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',pos2-11*sqr, ...
   'string',num2str(z(12)),...
   'Style','text', ...
	'Tag','H12','visible','off');

u1 = uicontrol('Position',pos3,...
   'string','kPa','style','text','Tag','U3');
u2 = uicontrol('Position',pos3-sqr,...
   'string','¢J','style','text','Tag','U2');    
u3 = uicontrol('Position',pos3-2*sqr,...
   'string','¢J','style','text','Tag','U3');    
u4 = uicontrol('Position',pos3-3*sqr,...
   'string','¢J','style','text','Tag','U4');    
u5 = uicontrol('Position',pos3-4*sqr,...
   'string','%','style','text','Tag','U5');
u6 = uicontrol('Position',pos3-5*sqr,...
   'string','%','style','text','Tag','U6');
u7 = uicontrol('Position',pos3-6*sqr,...
   'string','kPa','style','text','Tag','U7');
u8 = uicontrol('Position',pos3-7*sqr,...
   'string','kPa','style','text','Tag','U8');
u9 = uicontrol('Position',pos3-8*sqr,...
   'string','kg/kg','style','text','Tag','U9');
u10 = uicontrol('Position',pos3-9*sqr,...
   'string','kJ/kg','style','text','Tag','U10');
u11 = uicontrol('Position',pos3-10*sqr,...
   'string','m^3/kg','style','text','Tag','U11');
u12 = uicontrol('Position',pos3-11*sqr,...
   'string','kJ/kg','style','text','Tag','U12');

note2 = uicontrol('Position',pos4-1*sqr,...
   'string','-40<Tdb<70','style','text','Tag','Note2');    
note3 = uicontrol('Position',pos4-2*sqr,...
   'string','-40<Twb<Tdb','style','text','Tag','Note3');    
note4 = uicontrol('Position',pos4-3*sqr,...
   'string','-40<Twb<Tdp','style','text','Tag','Note4');    
note5 = uicontrol('Position',pos4-4*sqr,...
   'string','0<RH<100','style','text','Tag','Note5');
note8 = uicontrol('Position',pos4-7*sqr,...
   'style','text','Tag','Note8');
note9 = uicontrol('Position',pos4-8*sqr,...
   'style','text','Tag','Note9');    



act1 = uicontrol('Position',pos4-11*sqr,...
   'string','Ãö³¬','style','push','Tag','ACT1',...
   'callback','test1(''cbAct1'')');    

case 'cbTdb'
   f2=findobj(0,'tag','F2');
   h2=findobj(0,'tag','H2');
   global patm
   global rh
   global tdb
tdb=str2num(get(f2,'string'));
if tdb>70
   tdb=70;
elseif tdb<-40
   tdb=-40;
end
set(h2,'string',tdb,'style','text');
   PsyFixTdb;

case 'cbAct1'
   clear all;
   close all;

end