% This script loads and formats the raw data and column labels


%Import raw data from CR10X DAT file
fileToRead = 'C:\Documents and Settings\Batman\Desktop\Solar Cool\Data Collection & Analysis\LiCl\All Concentration.csv';
DELIMITER = ',';
HEADERLINES = 0;
rawdata = importdata(fileToRead, DELIMITER, HEADERLINES);

% Convert excel date serial into matlab format
MatlabDate = x2mdate(rawdata(:,1));
rawdata(:,1) = MatlabDate;

Des.ConcHdr = char(...
    'Cin',...
    'Cout',...
    'Rin',... 
    'Rout'...
    );

Des.DensHdr = char(...
    'DCin',...
    'DCout',...
    'DCin',... 
    'DCout'...
    );

Des.TempHdr = char(...
    'TCin',...
    'TCout',...
    'TRin',... 
    'TRout',...
    'THXRin',...
    'THXRout'...
    );

Des.Date = rawdata(:,1);

Des.Conc = [ ...
    rawdata(:,3) ...
    rawdata(:,5) ...
    rawdata(:,7) ...
    rawdata(:,9)
    ];

Des.Dens = [ ...
    rawdata(:,2) ...
    rawdata(:,4) ...
    rawdata(:,6) ...
    rawdata(:,8)
    ];

Des.Temp = [ ...
    DatedData(:,L.TDesCIn),...
    DatedData(:,L.TDesCOut),...    
    DatedData(:,L.TDesRIn),...
    DatedData(:,L.TDesROut),...    
    DatedData(:,L.TDesHIn),...
    DatedData(:,L.TDesHOut)...    
    ];  

clear fileToRead DELIMITER HEADERLINES labels MatlabDate rawdata