% START FIGURE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Figure 
figure  % 
hold on

% Start  sub plot plot
% temperatures; 
a1 = subplot(4,1,1);
plot(Date(TimeMask),...
        [...
        Air.Amb.Temp(TimeMask),...
        Air.Proc.Temp(TimeMask),...
        Air.Duct.Temp(TimeMask),...
        Hot.Temp.In(TimeMask),...
        Cold.Temp.In(TimeMask)...
        ],'LineWidth',2)
%set(gca,'XTick',[1,2,3,4,5,6]) % Doesn't work?
datetick('x',15)
ylabel('Temperature [C]')
xlabel('Time')
ylim([0 100]);
title('Air, cold water, hot water temperatures, in/out')
legend(...
    'Ambient','Process','Calibrated','Hot In','Cold In'...
    )
% End plot

% Start sub plot
% 3 Relative humidities; ambient, process, calibrated
a2 = subplot(4,1,2);
plot(DatedData(TimeMask,1),[...
    Air.Amb.RH(TimeMask),...
    Air.Proc.RH(TimeMask),...
    Air.Duct.RH(TimeMask)...
    ],'LineWidth',2)
%set(gca,'XTick',[1,2,3,4,5,6]) % Doesn't work?
datetick('x',15)
ylabel('Relative Humidity [%]')
xlabel('Time')
ylim([0 100]);
title('Relative humidities  in air stream')
legend(...
    'Ambient RH', ...
    'Process RH', ...
    'Duct RH'... 
    )
% End plot


% Start sub plot
% 3 
a3 = subplot(4,1,3);
plot(DatedData(TimeMask,1),[...
    Air.Amb.W(TimeMask),...
    Air.Proc.W(TimeMask),...
    Air.Duct.W(TimeMask)...
    ],'LineWidth',2)
%set(gca,'XTick',[1,2,3,4,5,6]) % Doesn't work?
datetick('x',15)
ylabel('Absosulte Humidity [kg/kg]')
xlabel('Time')
%ylim([0 100]);
title('Absolute humidities in air stream')
legend(...
    'Ambient W', ...
    'Process W', ...
    'Duct W'... 
    )
% End plot

% Start sub plot
% 3 
a4 = subplot(4,1,4);
plot(DatedData(TimeMask,1),[...
    Air.Amb.H(TimeMask),...
    Air.Proc.H(TimeMask),...
    Air.Duct.H(TimeMask)...
    ],'LineWidth',2)
%set(gca,'XTick',[1,2,3,4,5,6]) % Doesn't work?
datetick('x',15)
ylabel('Enthalpy [kJ/kg]')
xlabel('Time')
%ylim([0 100]);
title('Enthalpy in air stream')
legend(...
    'Ambient H', ...
    'Process H', ...
    'Duct H'... 
    )
% End plot

linkaxes([a1 a2 a3 a4], 'x');

hold off

% End plot
% END FIGURE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear a1 a2 a3 a4