% START FIGURE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Figure - Temps, Humidities, Enthalpies, of air
figure  % A three window plot
hold on

% Start  sub plot plot
% All enthalpies in conditioner
a1 = subplot(3,1,1);
plot(Date(TimeMask),...
        [...
        Enthalpy.Cond.Air.In(TimeMask),Enthalpy.Cond.Air.Out(TimeMask)...
        Enthalpy.Cond.CW.In(TimeMask),Enthalpy.Cond.CW.Out(TimeMask)...
        Enthalpy.Cond.Des.In(TimeMask),Enthalpy.Cond.Des.Out(TimeMask)...
        ],'LineWidth',2)
datetick('x',DateFormat1)
ylabel('Enthalpy [kg/hr]')
xlabel('Time')
ylim([-100 1E6]);
title('Conditioner Enthalpies')
legend(...
    'AirIn','AirOut','CWIn','CWOut','DesIn','DesOut'...
    )
% End plot

a2 = subplot(3,1,2);
plot(Date(TimeMask),...
        [...
        Enthalpy.Cond.Air.In(TimeMask) + ...
        Enthalpy.Cond.CW.In(TimeMask) + ...
        Enthalpy.Cond.Des.In(TimeMask), ...
        Enthalpy.Cond.Air.Out(TimeMask) + ...
        Enthalpy.Cond.CW.Out(TimeMask) + ...
        Enthalpy.Cond.Des.Out(TimeMask)...
        ],'LineWidth',2)
datetick('x',DateFormat1)
ylabel('Enthalpy [kg/hr]')
xlabel('Time')
ylim([-100 1E6]);
title('Conditioner Total Enthalpy Balance')
legend(...
    'Enthalpy Differential'...
    )
% End plot

a3 = subplot(3,1,3);
plot(Date(TimeMask),...
        ...
        Enthalpy.Cond.Air.In(TimeMask) ...
         + Enthalpy.Cond.CW.In(TimeMask) ...
         + Enthalpy.Cond.Des.In(TimeMask) ...
         - Enthalpy.Cond.Air.Out(TimeMask) ...
         - Enthalpy.Cond.CW.Out(TimeMask) ...
         - Enthalpy.Cond.Des.Out(TimeMask)...
        ,'LineWidth',2)
datetick('x',DateFormat1)
ylabel('Enthalpy [kg/hr]')
xlabel('Time')
ylim([-100 1E5]);
title('Conditioner Total Enthalpy Differential')
legend(...
    'Enthalpy In - Out'...
    )
% End plot

linkaxes([a1 a2 a3], 'x');
hold off

% End plot
% END FIGURE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear a1 a2 a3